# Generated by Django 6.0 on 2025-12-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_birth_date_customer_complete_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='confirmed_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True),
        ),
    ]
