# Generated by Django 6.0 on 2026-01-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.CharField(default='accounts/avatat_1', max_length=20),
        ),
    ]
