# Generated by Django 6.0 on 2026-01-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.CharField(default='accounts/avatar_none', max_length=20),
        ),
    ]
