# Generated by Django 6.0.1 on 2026-01-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_payment_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='external_id',
            new_name='payment_external_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='abacate_id',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_getway',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
