# Generated by Django 6.0.1 on 2026-01-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_rename_external_id_order_payment_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='external_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
