# Generated by Django 6.0.1 on 2026-01-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
