# Generated by Django 6.0.1 on 2026-01-13 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_order_payment_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_getway',
        ),
    ]
