# Generated by Django 6.0 on 2025-12-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_installments_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='installments_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
