# Generated by Django 6.0 on 2026-01-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_installments_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='archive',
            field=models.FileField(blank=True, null=True, upload_to='product_archives/'),
        ),
    ]
