# Generated by Django 6.0 on 2026-01-03 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_archive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='archive',
            new_name='file',
        ),
    ]
