# Generated by Django 6.0 on 2026-01-06 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_archive_product_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='installments_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='installments_value',
        ),
    ]
