# Generated by Django 6.0.1 on 2026-01-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='file',
        ),
        migrations.AddField(
            model_name='product',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
