# Generated by Django 5.2.8 on 2025-11-18 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria',
            new_name='Categoria',
        ),
    ]
